src/Entity/Contacts.php
<?php

namespace App\Entity;

use App\Repository\ContactsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContactsRepository::class)]
class Contacts
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 255)]
    private $email;

    #[ORM\Column(type: 'string', length: 255)]
    private $phone;

    #[ORM\Column(type: 'boolean')]
    private $is_active;

    #[ORM\Column(type: 'string', length: 255)]
    private $payee_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $account_number;

    #[ORM\Column(type: 'string', length: 255)]
    private $sort_code;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName($name): self
    {
        $this->name = $name;

        return $this;
    }


    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getPayeeName(): ?string
    {
        return $this->payee_name;
    }

    public function setPayeeName(string $payee_name): self
    {
        $this->payee_name = $payee_name;

        return $this;
    }

    public function getAccountNumber(): ?string
    {
        return $this->account_number;
    }

    public function setAccountNumber(string $account_number): self
    {
        $this->account_number = $account_number;

        return $this;
    }

    public function getSortCode(): ?string
    {
        return $this->sort_code;
    }

    public function setSortCode(string $sort_code): self
    {
        $this->sort_code = $sort_code;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Contacts;
use App\Entity\Course;
use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{

    #[Route(path: '/', name: 'app_home')]
    public function index(EntityManagerInterface $em): Response {
        $courseRepository = $em->getRepository(Course::class);
        $courses = $courseRepository->findBy([
            'is_active' => true,
        ], [
            'start_date' => 'DESC'
        ]);
        return $this->render('home/index.html.twig', [
            'courses' => $courses
        ]);
    }

    #[Route(path: '/courseRegister/{courseId}', name: 'app_course_register')]
    public function registerForCourse(int $courseId, EntityManagerInterface $em): Response {

        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $user = $this->getUser();

        $courseRepository = $em->getRepository(Course::class);

        $course = $courseRepository->find($courseId);
        if ($course === null || $course->isIsActive() === false) {
           return $this->render('404.html.twig');
        }

        $course->addUser($user);
        $em->flush();

        $contactsRepo = $em->getRepository(Contacts::class);
        $contacts = $contactsRepo->createQueryBuilder('c')
            ->andWhere('c.is_active = 1')->getQuery()->execute();
        return $this->render('home/course_register.html.twig', [
            'course' => $course,
            'contacts' => $contacts
        ]);
    }

    #[Route(path: '/courseDetails/{courseId}', name: 'app_course_details')]
    public function courseDetails(int $courseId, EntityManagerInterface $em): Response {
        $courseRepository = $em->getRepository(Course::class);
        $course = $courseRepository->find($courseId);
        if ($course === null || $course->isIsActive() === false) {
            return $this->render('404.html.twig');
        }

        return $this->render('home/course_details.html.twig', [
            'course' => $course
        ]);
    }
}

templates/home/course_details.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="courses-container">
        <div class="card">
            <div class="card-header">
                {{ course.name }}
            </div>
            <div class="card-body">
                <p>
                    {{ course.description }}
                </p>
                <p>
                    Price: &pound;{{ course.price }}
                </p>
                <p>
                    Duration: {{ course.getStartDate().format('d/m/Y H:i:s') }} - {{ course.getEndTime().format('d/m/Y H:i:s') }}
                </p>
            </div>
            <div class="card-footer">
                <a href="{{ path('app_course_register', {courseId: course.getId()}) }}" class="btn btn-primary">Register</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/home/course_register.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="card mt-5">
        <div class="card-body">
            <p>
                Successfully registered {{ app.user.email }} in course {{ course.name }}
            </p>

            <p>
                You will be enrolled in {{ course.name  }} after you send wire transfer of &pound;{{ course.price }}
                to one of the following bank accounts
            </p>
            {% for contact in contacts %}
                <table class="table">
                    <tr>
                        <th>Payee full name</th>
                        <td>{{ contact.payeeName }}</td>
                    </tr>
                    <tr>
                        <th>Sort code</th>
                        <td>{{ contact.sortCode }}</td>
                    </tr>
                    <tr>
                        <th>Account number</th>
                        <td>{{ contact.accountNumber }}</td>
                    </tr>
                    <tr>
                        <th>Reference</th>
                        <td>COURSE-{{ course.id }}</td>
                    </tr>
                </table>
            {% endfor %}


        </div>

    </div>
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div>
    <div id="my-carousel" class="carousel slide" data-bs-ride="carousel">
        {#<div class="carousel-indicators">
            #}{# <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-t#}{#
            <button data-bs-target="#my-carousel" data-bs-slide-to="0" aria-current="true" aria-label="Slide 1"></button>
            <button data-bs-target="#my-carousel" data-bs-slide-to="1" aria-current="false" aria-label="Slide 2"></button>
            <button data-bs-target="#my-carousel" data-bs-slide-to="2" aria-current="false" aria-label="Slide 3"></button>
            <button data-bs-target="#my-carousel" data-bs-slide-to="3" aria-current="false" aria-label="Slide 4"></button>
            <button data-bs-target="#my-carousel" data-bs-slide-to="4" aria-current="false" aria-label="Slide 5"></button>
        </div>#}
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="images/home-page-carousel/1.jpg" alt="" class="d-block w-100" height="">
            </div>
            <div class="carousel-item">
                <img src="images/home-page-carousel/2.jpg" alt="" class="d-block w-100">
            </div>
            <div class="carousel-item">
                <img src="images/home-page-carousel/3.jpg" alt="" class="d-block w-100">
            </div>
            <div class="carousel-item">
                <img src="images/home-page-carousel/4.jpg" alt="" class="d-block w-100">
            </div>
            <div class="carousel-item">
                <img src="images/home-page-carousel/5.jpg" alt="" class="d-block w-100">
            </div>
        </div>
        <button class="carousel-control-prev" data-bs-target="#my-carousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" data-bs-target="#my-carousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

<div class="courses-container">
    {% for course in courses %}
        <div class="card mt-3">
            <div class="card-header">
                {{ course.name }}
            </div>
            <div class="card-body">
                <p>
                    {{ course.description }}
                </p>
                <p>
                  Price: &pound;{{ course.price }}
                </p>
                <p>
                    Duration: {{ course.getStartDate().format('d/m/Y H:i:s') }} - {{ course.getEndTime().format('d/m/Y H:i:s') }}
                </p>
            </div>
            <div class="card-footer">
                <a href="{{ path('app_course_register', {courseId: course.getId()}) }}" class="btn btn-primary">Register</a>
            </div>
        </div>
    {% else %}
        <div>
            <p class="text-center fw-bold">
                <em>No courses yet<em>
            </p>
        </div>
    {% endfor %}
</div>
{% endblock %}